### ISSUE TITLE
Create new MD with updated analysis

### ISSUE THREAD

**Issue by sgosline** [sgosline/cytokineDrugResistance#1]
Start with MD 13 (doing the phospho analysis) with the following modifications:

1- remove all patients with Treatment='Trametinib Withdrawn' 
2- Create PCA plots of global and phospho for the late molm13 only, and the late molm 13 + parental 
3- redo KSEA analysis with p-values, and double check that correct parentals are used
- tram vs parental (late only)
- tram+mcp1 vs parental (late only)
- tram vs. tram+mcp1 (late only)
4- output boxplot data as TSV
5- create heatmap of substreates of selected kinases () across all conditions

**Comment by mdnestor** [comment]
PCA plots are done but KSEA needs to be revised
